# Generated by Django 6.0.3 on 2026-04-20 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='password_last_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
