# Generated by Django 6.0.3 on 2026-04-19 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lucid_spawn_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lucid',
            options={'ordering': ('party_slot', 'id')},
        ),
        migrations.AddField(
            model_name='lucid',
            name='level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lucid',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lucids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lucid',
            name='party_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lucid',
            name='pending_levelups',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lucid',
            name='upgrade_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='lucid',
            constraint=models.CheckConstraint(condition=models.Q(('party_slot__isnull', True), ('party_slot__in', [1, 2, 3]), _connector='OR'), name='lucid_valid_party_slot'),
        ),
        migrations.AddConstraint(
            model_name='lucid',
            constraint=models.UniqueConstraint(condition=models.Q(('party_slot__isnull', False)), fields=('owner', 'party_slot'), name='lucid_unique_party_slot_per_owner'),
        ),
    ]
