# Generated by Django 6.0.3 on 2026-04-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_alarm_wake_up_time_alter_alarm_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lucid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('types', models.JSONField(default=list)),
                ('description', models.CharField(max_length=1024)),
                ('evolution', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPoints', models.IntegerField(default=0)),
                ('currentWinStreak', models.IntegerField(default=0)),
                ('currentLoseStreak', models.IntegerField(default=0)),
                ('lucids', models.JSONField(default=list)),
                ('alarm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.alarm')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
